In [1]:
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

city_data_to_load = "city_data.csv"                             # File to Load 
ride_data_to_load = "ride_data.csv"                             # File to Load

city_df = pd.read_csv(city_data_to_load)                        # Read the City and Ride Data
ride_df = pd.read_csv(ride_data_to_load)

merge_df = pd.merge(ride_df, city_df, on="city", how="outer")   # Combine the data into a single dataset                                    

merged_city_type = merge_df.set_index("type")                   # Set the 'type' to be our index 
new=merged_city_type.reset_index()                              #new merged database with clean index
new.head(1000)                                                      #preview of the dataframe

,type,city,date,fare,ride_id,driver_count
0,Urban,Lake Jonathanshire,1/14/2018 10:14,13.83,5.739410e+12,5
1,Urban,Lake Jonathanshire,4/7/2018 20:51,31.25,4.441250e+12,5
2,Urban,Lake Jonathanshire,3/9/2018 23:45,19.89,2.389500e+12,5
3,Urban,Lake Jonathanshire,4/7/2018 18:09,24.28,7.796810e+12,5
4,Urban,Lake Jonathanshire,1/2/2018 14:14,13.89,4.242550e+11,5
5,Urban,Lake Jonathanshire,4/6/2018 11:30,16.84,6.164450e+12,5
6,Urban,Lake Jonathanshire,3/21/2018 0:18,37.95,8.353660e+12,5
7,Urban,Lake Jonathanshire,1/28/2018 0:07,5.67,9.756570e+12,5
8,Urban,Lake Jonathanshire,1/24/2018 12:24,34.65,3.319120e+12,5
9,Urban,Lake Jonathanshire,3/24/2018 16:27,14.94,1.670910e+12,5
10,Urban,Lake Jonathanshire,4/11/2018 22:10,12.81,5.999870e+12,5
11,Urban,Lake Jonathanshire,1/23/2018 21:43,21.11,7.711470e+12,5
12,Urban,Lake Jonathanshire,1/29/2018 0:19,41.05,6.649690e+12,5
13,Urban,Lake Jonathanshire,3/22/2018 14:33,18.72,4.675970e+12,5
14,Urban,Lake Jonathanshire,4/16/2018 20:26,32.47,1.013870e+12,5
15,Urban,Lake Jonathanshire,4/11/2018 19:49,25.92,8.533810e+12,5
16,Urban,Lake Jonathanshire,4/9/2018 21:41,15.96,5.772760e+11,5
17,Urban,Lake Jonathanshire,1/16/2018 9:27,26.27,3.267660e+12,5
18,Urban,Lake Jonathanshire,1/21/2018 12:12,37.25,2.966540e+12,5
19,Urban,Lake Jonathanshire,4/11/2018 21:32,22.48,3.505460e+12,5
20,Urban,Lake Jonathanshire,2/16/2018 1:49,17.58,3.641780e+12,5
21,Urban,Lake Jonathanshire,1/17/2018 13:15,28.42,6.544220e+12,5
22,Urban,Lake Jonathanshire,1/21/2018 9:48,22.36,2.522100e+12,5
23,Urban,Lake Jonathanshire,2/23/2018 6:10,26.63,5.372490e+12,5
24,Urban,South Michelleport,3/4/2018 18:24,30.24,2.343910e+12,72
25,Urban,South Michelleport,3/2/2018 9:54,33.12,8.138440e+11,72
26,Urban,South Michelleport,1/8/2018 9:38,23.77,4.916160e+12,72
27,Urban,South Michelleport,4/22/2018 3:15,43.62,4.663610e+12,72
28,Urban,South Michelleport,3/3/2018 16:13,41.62,2.339780e+12,72
29,Urban,South Michelleport,1/27/2018 19:38,15.45,7.465260e+12,72
...,...,...,...,...,...,...
970,Urban,Rogerston,3/7/2018 12:09,27.26,9.445960e+12,25
971,Urban,Rogerston,2/27/2018 3:58,27.40,6.535370e+12,25
972,Urban,Rogerston,1/26/2018 14:42,11.13,9.117400e+12,25
973,Urban,Rogerston,2/3/2018 21:09,4.41,1.718710e+12,25
974,Urban,West Ericstad,4/24/2018 3:20,7.31,4.292480e+12,25
975,Urban,West Ericstad,4/4/2018 13:03,28.52,6.432850e+12,25
976,Urban,West Ericstad,1/25/2018 12:29,20.03,3.276480e+12,25
977,Urban,West Ericstad,1/8/2018 9:03,32.99,6.688340e+12,25
978,Urban,West Ericstad,3/28/2018 13:29,22.28,3.135270e+12,25
979,Urban,West Ericstad,1/23/2018 10:13,10.12,8.035850e+12,25
980,Urban,West Ericstad,4/13/2018 9:52,22.39,5.770760e+12,25
981,Urban,West Ericstad,4/19/2018 20:35,5.75,3.497130e+12,25
982,Urban,West Ericstad,3/29/2018 4:59,40.29,8.095030e+11,25
983,Urban,West Ericstad,3/21/2018 9:28,18.24,4.602950e+12,25
984,Urban,West Ericstad,1/25/2018 20:18,23.27,2.128080e+12,25
985,Urban,West Ericstad,4/12/2018 12:08,27.69,4.567960e+12,25
986,Urban,West Ericstad,1/27/2018 4:30,29.05,7.599450e+12,25
987,Urban,West Ericstad,2/5/2018 15:30,30.89,2.464030e+12,25
988,Urban,West Ericstad,5/5/2018 0:44,7.76,8.379000e+12,25
989,Urban,West Ericstad,3/18/2018 15:28,23.62,6.209240e+12,25
990,Urban,West Ericstad,3/4/2018 12:31,43.98,6.434940e+12,25
991,Urban,West Ericstad,1/21/2018 12:14,8.07,7.506040e+12,25
992,Urban,Hurleymouth,5/4/2018 21:50,21.44,4.039660e+12,36
993,Urban,Hurleymouth,3/22/2018 11:19,32.85,8.449290e+12,36
994,Urban,Hurleymouth,3/3/2018 11:28,36.31,1.670350e+11,36
995,Urban,Hurleymouth,3/26/2018 20:22,41.15,4.707260e+12,36
996,Urban,Hurleymouth,2/20/2018 10:47,17.07,7.023700e+12,36
997,Urban,Hurleymouth,1/12/2018 1:19,10.64,8.125600e+12,36
998,Urban,Hurleymouth,3/17/2018 6:50,29.95,5.225180e+12,36
999,Urban,Hurleymouth,4/1/2018 6:26,9.94,4.063430e+12,36

In [ ]:
#Creating series for rides per city for the three city types
rides_per_city_urban = new.loc[new["type"]== "Urban", :].groupby('city').count().ride_id 
rides_per_city_rural = new.loc[new["type"]== "Rural", :].groupby('city').count().ride_id  
rides_per_city_suburban = new.loc[new["type"]== "Suburban", :].groupby('city').count().ride_id  

#Creating series for average fare per city for the three city types
average_fare_city_urban = new.loc[new["type"]== "Urban", :].groupby('city').mean().fare  
average_fare_city_rural = new.loc[new["type"]== "Rural", :].groupby('city').mean().fare 
average_fare_city_suburban = new.loc[new["type"]== "Suburban", :].groupby('city').mean().fare  

#Creating series for driver count per city for the three city types
drivers_by_city_urban = new.loc[new["type"]== "Urban", :].groupby('city').sum().driver_count  
drivers_by_city_rural = new.loc[new["type"]== "Rural", :].groupby('city').sum().driver_count  
drivers_by_city_suburban = new.loc[new["type"]== "Suburban", :].groupby('city').sum().driver_count  

#new dataframe for city type urban
results_by_city_urban=pd.DataFrame({"Average Fare per City":average_fare_city_urban, 
                "Total Rides per City":rides_per_city_urban,
                 "Driver Count":drivers_by_city_urban})

#new dataframe for city type rural
results_by_city_rural=pd.DataFrame({"Average Fare per City":average_fare_city_rural, 
                "Total Rides per City":rides_per_city_rural,
                 "Driver Count":drivers_by_city_rural})

#new dataframe for suburban
results_by_city_suburban=pd.DataFrame({"Average Fare per City":average_fare_city_suburban, 
                "Total Rides per City":rides_per_city_suburban,
                 "Driver Count":drivers_by_city_suburban})

## Bubble Plot of Ride Sharing Data

In [ ]:
#Creating the combined scatter plot for the three city types
ax=results_by_city_rural.plot(kind='scatter', x='Total Rides per City', y='Average Fare per City',
                           color='Yellow', label='Rural',edgecolor="black",alpha=0.5,grid=True,figsize=(8,6),
                           s=results_by_city_rural['Driver Count']);
results_by_city_suburban.plot(kind='scatter', x='Total Rides per City', y='Average Fare per City',
                           color='LightBlue', label='Suburban',edgecolor="black",ax=ax,alpha=0.5,grid=True,figsize=(8,6),
                           s=results_by_city_suburban['Driver Count']);
results_by_city_urban.plot(kind='scatter', x='Total Rides per City', y='Average Fare per City',
                           color='Red', label='Urban',edgecolor="black",ax=ax, alpha=0.5,grid=True,figsize=(8,6),
                           s=results_by_city_urban['Driver Count'],title="Pyber Ride Sharing Data 2016")

# add text annotation
ax.text(43, 40, "Circle size correlates with driver count per City", horizontalalignment='left', size='medium', 
        color='black', weight='semibold')
ax.text(43, 41, "Note:", horizontalalignment='left', size='medium', 
        color='black', weight='semibold')

ax.legend(markerscale=0.4)
plt.savefig("Pyber Ride Sharing Data 2016.png")
plt.show

## Total Rides by City Type

In [ ]:
# Calculate Type Percents
percentages_by_type_urban=new.loc[new["type"]== "Urban", :].sum().fare 
percentages_by_type_rural=new.loc[new["type"]== "Rural", :].sum().fare
percentages_by_type_suburban=new.loc[new["type"]== "Suburban", :].sum().fare
total_fares_by_city_type=new['fare'].sum()

pie_urban=percentages_by_type_urban/total_fares_by_city_type
pie_rural=percentages_by_type_rural/total_fares_by_city_type
pie_suburban=percentages_by_type_suburban/total_fares_by_city_type

# Build Pie Chart
labels = ["Urban", "Rural", "Suburban"]
sizes = [pie_urban, pie_rural, pie_suburban]
colors = ["lightcoral", "orange", "lightskyblue"]
explode = (0.1, 0, 0)

plt.title("% of Total Fares by City Type")
plt.pie(sizes, explode=explode, labels=labels, colors=colors,
        autopct="%1.1f%%", shadow=True, startangle=280)

# Save Figure
plt.savefig("Percentage of Total Fares by City Type.png")

In [ ]:
# Calculate Ride Percents
rides_by_type_urban=new.loc[new["type"]== "Urban", :].count().fare 
rides_by_type_rural=new.loc[new["type"]== "Rural", :].count().fare
rides_by_type_suburban=new.loc[new["type"]== "Suburban", :].count().fare
total_rides_by_city_type=new['fare'].count()

pie_urban2=rides_by_type_urban/total_rides_by_city_type
pie_rural2=rides_by_type_rural/total_rides_by_city_type
pie_suburban2=rides_by_type_suburban/total_rides_by_city_type

# Build Pie Chart
labels = ["Urban", "Rural", "Suburban"]
sizes = [pie_urban2, pie_rural2, pie_suburban2]
colors = ["lightcoral", "orange", "lightskyblue"]
explode = (0.1, 0, 0)

plt.title("% of Total Rides by City Type")
plt.pie(sizes, explode=explode, labels=labels, colors=colors,
        autopct="%1.1f%%", shadow=True, startangle=260)

# Save Figure
plt.savefig("Percentage of Total Rides by City Type.png")

## Total Drivers by City Type

In [ ]:
# Calculate drivers Percents
driver_by_type_urban=new.loc[new["type"]== "Urban", :].sum().driver_count 
driver_by_type_rural=new.loc[new["type"]== "Rural", :].sum().driver_count
driver_by_type_suburban=new.loc[new["type"]== "Suburban", :].sum().driver_count
total_drivers_by_city_type=new['driver_count'].sum()

pie_urban3=driver_by_type_urban/total_drivers_by_city_type
pie_rural3=driver_by_type_rural/total_drivers_by_city_type
pie_suburban3=driver_by_type_suburban/total_drivers_by_city_type

# Build Pie Chart
labels = ["Urban", "Rural", "Suburban"]
sizes = [pie_urban3, pie_rural3, pie_suburban3]
colors = ["lightcoral", "orange", "lightskyblue"]
explode = (0.1, 0, 0)

plt.title("% of Total Drivers by City Type")
plt.pie(sizes, explode=explode, labels=labels, colors=colors,
        autopct="%1.1f%%", shadow=True, startangle=220)

# Save Figure
plt.savefig("Percentage of Total Drivers by City Type.png")

In [2]:
driver_by_type_urban=city_df.loc[city_df["type"]== "Urban", :].driver_count.sum()
percentages_by_type_urban=city_df.loc[city_df["type"]== "Urban", :].sum().fare 
driver_by_type_urban

AttributeError: 'Series' object has no attribute 'fare'

In [ ]:
test=new['driver_count']*1.0
test.head(1000)

In [ ]:
# Show Figure
plt.show()